### ISSUE TITLE
Migrate m3u folder to Kotlin 🚀 

### ISSUE THREAD

**Issue by enzoftware** [enzoftware/android_iptv#5]
Migrate the [m3u](https://github.com/enzoftware/android_iptv/tree/master/app/src/main/java/com/enzoftware/androidiptv/m3u) folder to Kotlin

**Comment by DeKaN** [comment]
Can I take this issue?

**Comment by Rishavgupta12345** [comment]
can i work on it

**Comment by ghost** [comment]
I want to solve this issue

**Comment by JudahSolomon** [comment]
I want to do the conversion

**Comment by enzoftware** [comment]
Hi everyone 👋  , 

I appreciate your enthusiasm for contributing to the project 😸  Any of you could work on this issue, just send the pull request and I'll review it. 

Obviously, just one could be merged into this project, but if the other approaches are enough good I can mark them as `hacktoberfest-accepted` label to make this work for you.

Any discussion or question about this task, just let it know in the comments and we can find the best approach together.

Have a good time 👍
